### ISSUE TITLE
Alternative registration/login system

### ISSUE THREAD

**Issue by typonaut** [slyapustin/django-classified-demo#94]
I have nearly completed a log-in/registration system with all_auth, which seems a lot more sophisticated than social_auth, do you want to substitute that in for the existing demo given the security issue with social_auth?

**Comment by inoks** [comment]
@typonaut Yes, that would be awesome. 
Please create PR.

**Comment by typonaut** [comment]
I have this functional, I just have to sort out some style issues.

**Comment by typonaut** [comment]
Have initiated pull request, couldn’t link to this issue. 

https://github.com/slyapustin/django-classified-demo/pull/99
